# Usa la imagen oficial de MySQL 8
FROM mysql:8.0

# Establece variables de entorno para MySQL
ENV MYSQL_ROOT_PASSWORD=root
ENV MYSQL_DATABASE=mibase1
ENV MYSQL_USER=root
ENV MYSQL_PASSWORD=Canada

# Exponer el puerto 3306
EXPOSE 3306
